"use client";

export interface Paper {
  title: string;
  authors: string;
  date: string;
  showAuthors: boolean;
  description: string;
  upvotes: string;
  repos: string;
  citations: string;
  tags: { label: string; color: string }[];
  methods: string[];
  sotaBenchmarks: string[];
  sotaRank: string;
  sotaRankLabel: string;
  sotaExtra: string;
  thumbUrl: string;
}

export const PAPERS: Paper[] = [
  {
    title: "GLM-5.2: Built for Long-Horizon Tasks",
    authors: "Z.ai Team",
    date: "Jun 16, 2026",
    showAuthors: true,
    description: "GLM-5.2 is Z.ai's latest flagship open-weight model for long-horizon agentic engineering. The release extends GLM-5.1 with a solid 1M-token context, IndexShare sparse-attention efficiency, improved MTP speculative decoding, and flexible thinking-effort controls. Benchmarks report stronger coding and agentic performance on SWE-Bench Pro, Terminal-Bench, and MCPAtlas.",
    upvotes: "11.2K",
    repos: "11.3K",
    citations: "30",
    tags: [
      { label: "Agents", color: "blue" },
      { label: "Coding Agents", color: "purple" },
      { label: "Language Modeling", color: "green" },
      { label: "Math", color: "yellow" },
      { label: "World Knowledge", color: "orange" },
    ],
    methods: ["DeepSeek Sparse Attention", "MCP", "Mixture-of-Experts (MoE)", "Transformer"],
    sotaBenchmarks: ["AIME 2026", "HMMT Feb 2026", "PostTrainBench"],
    sotaRank: "3",
    sotaRankLabel: "FrontierSWE, NL2Repo",
    sotaExtra: "",
    thumbUrl: "/img1.png",
  },
  {
    title: "IndexCache: Accelerating Sparse Attention via Cross-Layer Index Reuse",
    authors: "Yushi Bai, Qian Dong, Ting Jiang, +5 authors",
    date: "Mar 12, 2026",
    showAuthors: true,
    description: "Long-context agentic workflows have emerged as a defining use case for large language models, making attention efficiency critical for both inference speed and serving cost. Sparse attention addresses this challenge effectively, and DeepSeek Sparse Attention (DSA) is a representative production-grade solution: a lightweight lightning indexer selects the most relevant KV pairs per layer without recomputing full attention.",
    upvotes: "8.4K",
    repos: "8.5K",
    citations: "10",
    tags: [
      { label: "Language Modeling", color: "green" },
      { label: "Long Context", color: "purple" },
      { label: "Efficiency", color: "blue" },
    ],
    methods: ["DeepSeek Sparse Attention", "Gated DeltaNet", "Key-value cache", "Kimi Delta Attention"],
    sotaBenchmarks: ["LongBench"],
    sotaRank: "2",
    sotaRankLabel: "RULER (128K)",
    sotaExtra: "",
    thumbUrl: "/img2.png",
  },
  {
    title: "Darwin Family: MRI-Trust-Weighted Evolutionary Merging for Training-Free Scaling of Language-Model Reasoning",
    authors: "Taebong Kim, Youngsik Hong, Minsik Kim, +4 authors",
    date: "May 14, 2026",
    showAuthors: true,
    description: "We present Darwin Family, a framework for training-free evolutionary merging of large language models via gradient-free weight-space recombination. We ask whether frontier-level reasoning performance can be improved without additional training, by reorganizing latent capabilities already encoded in existing checkpoints.",
    upvotes: "7.1K",
    repos: "7.2K",
    citations: "24",
    tags: [
      { label: "Language Modeling", color: "green" },
      { label: "Reasoning", color: "purple" },
      { label: "Model Merging", color: "orange" },
    ],
    methods: ["Mamba", "Post-training", "Transformer"],
    sotaBenchmarks: ["Natural Questions"],
    sotaRank: "3",
    sotaRankLabel: "CommonsenseQA",
    sotaExtra: "",
    thumbUrl: "/img3.png",
  },
  {
    title: "Qwen3.5: Towards Native Multimodal Agents",
    authors: "Qwen Team",
    date: "Feb 16, 2026",
    showAuthors: true,
    description: "Qwen3.5 release blog introducing the open-weight Qwen3.5-397B-A17B native vision-language model and reporting benchmark evaluations across language, coding, agents, multimodal understanding, and video understanding tasks at scale.It highlights significant performance improvements across benchmarks.",
    upvotes: "9.8K",
    repos: "9.9K",
    citations: "8",
    tags: [
      { label: "Agents", color: "blue" },
      { label: "Image Understanding", color: "blue" },
      { label: "Language Modeling", color: "green" },
      { label: "Video Classification", color: "purple" },
    ],
    methods: ["Qwen3", "Mixture-of-Experts (MoE)", "Post-training"],
    sotaBenchmarks: ["C-Eval", "IFEval", "MathVista", "MMLU-Pro"],
    sotaRank: "",
    sotaRankLabel: "",
    sotaExtra: "+20 more",
    thumbUrl: "/img4.png",
  },
  {
    title: "LTX-2: Efficient Joint Audio-Visual Foundation Model",
    authors: "Yoav HaCohen, Benny Brazowski, Nisan Chiprut, +26 authors",
    date: "Jan 6, 2026",
    showAuthors: true,
    description: "We introduce LTX-2, an open-source foundational model capable of generating high-quality, temporally synchronized audiovisual content in a unified manner. Recent text-to-video diffusion models remain silent — LTX-2 closes this gap by jointly modeling visual and audio streams end-to-end with a shared diffusion backbone.",
    upvotes: "6.3K",
    repos: "6.4K",
    citations: "98",
    tags: [
      { label: "Audio Generation", color: "blue" },
      { label: "Video Generation", color: "purple" },
      { label: "Multimodal", color: "orange" },
    ],
    methods: ["Classifier-free guidance", "Diffusion", "Diffusion Transformer (DiT)", "Flow matching"],
    sotaBenchmarks: ["EvalCrafter", "VBench"],
    sotaRank: "2",
    sotaRankLabel: "AudioCaps",
    sotaExtra: "",
    thumbUrl: "/img1.png",
  },
  {
    title: "NVIDIA Nemotron 3: Efficient and Open Intelligence",
    authors: "Nvidia, Aaron Blakeman, Aaron Grattafiori, +355 authors",
    date: "Dec 24, 2025",
    showAuthors: true,
    description: "We introduce the Nemotron 3 family — Nano, Super, and Ultra — delivering strong agentic, reasoning, and conversational capabilities. The Nemotron 3 family uses a Mixture-of-Experts hybrid Mamba-Transformer architecture to provide best-in-class throughput and context lengths of up to 1M tokens.",
    upvotes: "12.5K",
    repos: "12.6K",
    citations: "22",
    tags: [
      { label: "Agents", color: "blue" },
      { label: "Language Modeling", color: "green" },
      { label: "Reinforcement Learning", color: "blue" },
    ],
    methods: ["Function calling", "GRPO", "Mamba", "Mixture-of-Experts (MoE)"],
    sotaBenchmarks: ["LiveCodeBench (v5)", "RULER", "TauBench"],
    sotaRank: "2",
    sotaRankLabel: "WMT24++",
    sotaExtra: "#3 on AIME 2025",
    thumbUrl: "/img2.png",
  },
  {
    title: "DFlash: Block Diffusion for Flash Speculative Decoding",
    authors: "Jian Chen, Yesheng Liang, Zhijian Liu",
    date: "Feb 5, 2026",
    showAuthors: true,
    description: "Autoregressive large language models (LLMs) deliver strong performance but require inherently sequential decoding, leading to high inference latency and poor GPU utilization. Speculative decoding mitigates this bottleneck by using a fast draft model whose outputs are verified in parallel by the target LLM.",
    upvotes: "5.2K",
    repos: "5.3K",
    citations: "33",
    tags: [
      { label: "Language Modeling", color: "green" },
      { label: "Efficiency", color: "blue" },
      { label: "Inference", color: "blue" },
    ],
    methods: ["DeepSeek-R1", "Diffusion", "Speculative decoding"],
    sotaBenchmarks: ["HumanEval"],
    sotaRank: "3",
    sotaRankLabel: "Spec-Bench",
    sotaExtra: "",
    thumbUrl: "/img3.png",
  },
  {
    title: "Tmax: A simple recipe for terminal agents",
    authors: "Hamish Ivison, Junjie Oscar Yin, Rulin Shao, +3 authors",
    date: "Jun 22, 2026",
    showAuthors: true,
    description: "Terminal-using agents have quickly become the most popular downstream application of language models. Despite their prevalence, relatively little academic work has examined RL-based training of these models. We present Tmax, the strongest open RL recipe for terminal agents to date.",
    upvotes: "4.8K",
    repos: "4.9K",
    citations: "12",
    tags: [
      { label: "Coding Agents", color: "purple" },
      { label: "Language Modeling", color: "green" },
      { label: "Reinforcement Learning", color: "blue" },
    ],
    methods: ["Fine-tuning", "GRPO", "Post-training"],
    sotaBenchmarks: ["SWE-Bench Verified"],
    sotaRank: "2",
    sotaRankLabel: "Terminal-Bench",
    sotaExtra: "",
    thumbUrl: "/img4.png",
  },
  {
    title: "Qwen3.6",
    authors: "Qwen",
    date: "Apr 21, 2026",
    showAuthors: true,
    description: "Qwen3.6 is an open-weight model focused on agentic coding, repository-level reasoning, long-context usage, and multimodal language-model capabilities. The release includes 35B-A3B and 27B base models plus their FP8 quantized variants for efficient local deployment.",
    upvotes: "8.9K",
    repos: "9.0K",
    citations: "4",
    tags: [
      { label: "Agents", color: "blue" },
      { label: "Image Understanding", color: "blue" },
      { label: "Language Modeling", color: "green" },
      { label: "Coding Agents", color: "purple" },
    ],
    methods: ["fp8", "Mixture-of-Experts (MoE)", "Multi-head attention", "Qwen3"],
    sotaBenchmarks: ["RealWorldQA", "Video-MME"],
    sotaRank: "2",
    sotaRankLabel: "Claw-Eval, MMBench-V1.1",
    sotaExtra: "+1 more",
    thumbUrl: "/img1.png",
  },
  {
    title: "VibeThinker-3B: Exploring the Frontier of Verifiable Reasoning in Small Language Models",
    authors: "Sen Xu, Shixi Liu, Wei Wang, +6 authors",
    date: "Jun 15, 2026",
    showAuthors: true,
    description: "This technical report introduces VibeThinker-3B, a compact dense model with 3B parameters developed to investigate how far verifiable reasoning can be pushed within a strictly small-model regime. We systematically enhance the model through an optimized pipeline including curriculum-based training and reward shaping.",
    upvotes: "3.9K",
    repos: "4.0K",
    citations: "17",
    tags: [
      { label: "Language Modeling", color: "green" },
      { label: "Reasoning", color: "purple" },
      { label: "Reinforcement Learning", color: "blue" },
    ],
    methods: ["DeepSeek Sparse Attention", "Fine-tuning", "GRPO", "Post-training", "Test-time scaling"],
    sotaBenchmarks: [],
    sotaRank: "2",
    sotaRankLabel: "AIME 2026",
    sotaExtra: "#3 on IFEval",
    thumbUrl: "/img2.png",
  },
  {
    title: "Qwen3-TTS Technical Report",
    authors: "Hangrui Hu, Xinfa Zhu, Ting He, +13 authors",
    date: "Jan 22, 2026",
    showAuthors: true,
    description: "We present the Qwen3-TTS series, a family of advanced multilingual, controllable, robust, and streaming text-to-speech models. Qwen3-TTS supports state-of-the-art 3-second voice cloning and description-based control, enabling fine-grained manipulation over output speech prosody, style, and speaker identity.",
    upvotes: "5.6K",
    repos: "5.7K",
    citations: "59",
    tags: [
      { label: "Audio Generation", color: "blue" },
      { label: "Text To Speech", color: "green" },
      { label: "Voice Cloning", color: "purple" },
    ],
    methods: ["Diffusion Transformer (DiT)", "Direct Preference Optimization (DPO)", "Flow matching"],
    sotaBenchmarks: ["LibriSpeech", "UTMOS"],
    sotaRank: "2",
    sotaRankLabel: "VoiceBench",
    sotaExtra: "",
    thumbUrl: "/img3.png",
  },
  {
    title: "QUEST: Training Frontier Deep Research Agents with Fully Synthetic Tasks",
    authors: "Jian Xie, Tianhe Lin, Zilu Wang, +16 authors",
    date: "May 22, 2026",
    showAuthors: true,
    description: "Deep research agents extend the role of search engines from retrieving keyword-matched pages to synthesizing knowledge. We propose QUEST, a fully synthetic task generation pipeline for training open deep research agents that generalize across diverse task types and domains.",
    upvotes: "6.7K",
    repos: "6.8K",
    citations: "10",
    tags: [
      { label: "Agents", color: "blue" },
      { label: "Reinforcement Learning", color: "blue" },
      { label: "Reasoning", color: "purple" },
    ],
    methods: ["Deep Research", "DeepSeek-R1", "Direct Preference Optimization (DPO)", "Fine-tuning"],
    sotaBenchmarks: ["GAIA"],
    sotaRank: "2",
    sotaRankLabel: "BrowseComp-Plus",
    sotaExtra: "",
    thumbUrl: "/img4.png",
  },
  {
    title: "Data Science and Technology Towards AGI Part I: Tiered Data Management",
    authors: "Yudong Wang, Zixuan Fu, Hengyu Zhao, +14 authors",
    date: "Feb 9, 2026",
    showAuthors: true,
    description: "The development of artificial intelligence can be viewed as an evolution of data-driven learning paradigms. We propose a tiered data management framework that moves beyond unidirectional data scaling, enabling more structured and efficient data curation for LLM pretraining.",
    upvotes: "4.3K",
    repos: "4.4K",
    citations: "17",
    tags: [
      { label: "Language Modeling", color: "green" },
      { label: "Data Curation", color: "orange" },
      { label: "Pretraining", color: "blue" },
    ],
    methods: ["DeepSeek-R1", "Direct Preference Optimization (DPO)", "GRPO", "Key-value cache"],
    sotaBenchmarks: ["MMLU-Pro"],
    sotaRank: "3",
    sotaRankLabel: "HellaSwag",
    sotaExtra: "",
    thumbUrl: "/img1.png",
  },
  {
    title: "MiniMax Sparse Attention",
    authors: "Xunhao Lai, Weiqi Xu, Yufeng Yang, +8 authors",
    date: "Jun 11, 2026",
    showAuthors: true,
    description: "Ultra-long-context capability is becoming indispensable for frontier LLMs. We introduce MiniMax Sparse Attention, a production-grade sparse attention mechanism targeting hundreds-of-thousands to millions of tokens, achieving quadratic cost reduction without degrading downstream task accuracy.",
    upvotes: "5.1K",
    repos: "5.2K",
    citations: "17",
    tags: [
      { label: "Language Modeling", color: "green" },
      { label: "Long Context", color: "purple" },
      { label: "Efficiency", color: "blue" },
    ],
    methods: ["Big Bird", "Flash Attention", "Gated DeltaNet", "Grouped-Query Attention"],
    sotaBenchmarks: ["RULER"],
    sotaRank: "2",
    sotaRankLabel: "LongBench (1M)",
    sotaExtra: "",
    thumbUrl: "/img2.png",
  },
  {
    title: "MOSS-TTS Technical Report",
    authors: "Yitian Gong, Botian Jiang, Yiwei Zhao, +23 authors",
    date: "Mar 18, 2026",
    showAuthors: true,
    description: "We present MOSS-TTS, a speech generation foundation model built on discrete audio tokens, autoregressive modeling, and large-scale pretraining. Built on MOSS-Audio-Tokenizer, it compresses 24 kHz audio to 12.5 fps with variable-bitrate RVQ and unified semantic-acoustic encoding.",
    upvotes: "3.8K",
    repos: "3.9K",
    citations: "4",
    tags: [
      { label: "Audio Generation", color: "blue" },
      { label: "Text To Speech", color: "green" },
      { label: "Voice Cloning", color: "purple" },
    ],
    methods: ["Pre-training", "Qwen3", "Scaling Laws", "SoundStream", "Transformer", "WaveNet"],
    sotaBenchmarks: ["UTMOS"],
    sotaRank: "3",
    sotaRankLabel: "LibriSpeech (WER)",
    sotaExtra: "",
    thumbUrl: "/img3.png",
  },
  {
    title: "DeepSeek-V4: Towards Highly Efficient Million-Token Context Intelligence",
    authors: "DeepSeek-AI",
    date: "Apr 24, 2026",
    showAuthors: true,
    description: "We present DeepSeek-V4 series, including two strong Mixture-of-Experts language models: DeepSeek-V4-Pro with 1.6T parameters (49B activated) and DeepSeek-V4-Flash with 284B parameters (13B activated), both supporting a context length of one million tokens with key architectural upgrades.",
    upvotes: "15.2K",
    repos: "15.3K",
    citations: "4",
    tags: [
      { label: "Agents", color: "blue" },
      { label: "Language Modeling", color: "green" },
      { label: "Long Context", color: "purple" },
      { label: "Coding Agents", color: "purple" },
    ],
    methods: ["Mixture-of-Experts (MoE)", "Post-training", "Sparse attention", "Transformer"],
    sotaBenchmarks: ["LiveCodeBench (v6)", "MRCR v2 (1M)"],
    sotaRank: "2",
    sotaRankLabel: "MMLU-Pro",
    sotaExtra: "",
    thumbUrl: "/img4.png",
  },
  {
    title: "Holo3.1: Fast & Local Computer Use Agents",
    authors: "Holo Team",
    date: "Jun 1, 2026",
    showAuthors: true,
    description: "Holo3.1 improves robustness across web, desktop, and mobile environments as well as agent frameworks. It introduces native function-calling support alongside quantized checkpoints (FP8, Q4 GGUF, NVFP4) for local inference on consumer hardware, with new small model sizes (0.8B, 4B).",
    upvotes: "7.3K",
    repos: "7.4K",
    citations: "7",
    tags: [
      { label: "Agents", color: "blue" },
      { label: "Computer Use", color: "green" },
      { label: "Image Understanding", color: "blue" },
      { label: "Language Modeling", color: "green" },
    ],
    methods: ["Function calling", "Mixture-of-Experts (MoE)", "Qwen3"],
    sotaBenchmarks: ["AndroidWorld", "OSWorld"],
    sotaRank: "2",
    sotaRankLabel: "OSW-G (OSWorld-G)",
    sotaExtra: "",
    thumbUrl: "/img1.png",
  },
  {
    title: "FastContext: Training Efficient Repository Explorer for Coding Agents",
    authors: "Shaoqiu Zhang, Maoquan Wang, Yuling Shi, +5 authors",
    date: "Jun 12, 2026",
    showAuthors: true,
    description: "LLM coding agents achieve strong results on software engineering tasks, yet repository exploration remains a major bottleneck. We train a dedicated lightweight explorer model that locates relevant code efficiently, freeing the main agent's context budget for actual problem-solving.",
    upvotes: "4.1K",
    repos: "4.2K",
    citations: "10",
    tags: [
      { label: "Coding Agents", color: "purple" },
      { label: "Language Modeling", color: "green" },
      { label: "Question Answering", color: "blue" },
    ],
    methods: ["Fine-tuning", "GRPO", "Post-training"],
    sotaBenchmarks: ["SWE-Bench Verified"],
    sotaRank: "3",
    sotaRankLabel: "RepoQA",
    sotaExtra: "",
    thumbUrl: "/img2.png",
  },
  {
    title: "Beyond Benchmarks: MathArena as an Evaluation Platform for Mathematics with LLMs",
    authors: "Dekoninck, Jasper, Jovanović, Nikola, Gehrunger, Tim, +4 authors",
    date: "May 1, 2026",
    showAuthors: true,
    description: "Large language models are becoming increasingly capable mathematical collaborators, but static benchmarks are no longer sufficient. We introduce MathArena, a living evaluation platform with regularly updated competition problems that prevents saturation and enables reliable model comparison over time.",
    upvotes: "3.5K",
    repos: "3.6K",
    citations: "28",
    tags: [
      { label: "Language Modeling", color: "green" },
      { label: "Math", color: "yellow" },
      { label: "Reasoning", color: "purple" },
    ],
    methods: ["Chain-of-Thought (CoT)", "Test-time scaling"],
    sotaBenchmarks: ["MathArena"],
    sotaRank: "2",
    sotaRankLabel: "AIME 2026",
    sotaExtra: "",
    thumbUrl: "/img3.png",
  },
  {
    title: "ACE-Step 1.5: Pushing the Boundaries of Open-Source Music Generation",
    authors: "Junmin Gong, Yulin Song, Wenxiao Zhao, +3 authors",
    date: "Jan 31, 2026",
    showAuthors: true,
    description: "We present ACE-Step v1.5, a highly efficient open-source music foundation model that delivers commercial-grade generation on consumer hardware. ACE-Step v1.5 generates a full song under 2 seconds on an A100 and under 10 seconds on a consumer GPU while matching or exceeding commercial music models on standard metrics.",
    upvotes: "6.2K",
    repos: "6.3K",
    citations: "11",
    tags: [
      { label: "Audio Generation", color: "blue" },
      { label: "Language Modeling", color: "green" },
      { label: "Reinforcement Learning", color: "blue" },
    ],
    methods: ["Chain-of-Thought (CoT)", "Diffusion Transformer (DiT)", "LoRa", "Reward model"],
    sotaBenchmarks: ["MusicCaps"],
    sotaRank: "2",
    sotaRankLabel: "Song Describer Dataset",
    sotaExtra: "",
    thumbUrl: "/img4.png",
  },
  {
    title: "Mix, MinHash, and Match: Cross-Source Agreement for Multilingual Pretraining Datasets",
    authors: "Sultan Alrashed, Francesco Orabona",
    date: "Dec 21, 2025",
    showAuthors: true,
    description: "Multilingual data from the web is essential for LLM pretraining, yet scraping it is expensive and research groups repeatedly crawl the same content. We found that over 40% of tokens across major Arabic web corpora are duplicated between sources, and propose using this redundancy as a quality signal for building high-quality multilingual datasets.",
    upvotes: "2.9K",
    repos: "3.0K",
    citations: "14",
    tags: [
      { label: "Language Modeling", color: "green" },
      { label: "Pretraining", color: "blue" },
      { label: "Data Curation", color: "orange" },
    ],
    methods: ["Pre-training", "T5"],
    sotaBenchmarks: ["mC4"],
    sotaRank: "3",
    sotaRankLabel: "Arabic NLP Benchmark",
    sotaExtra: "",
    thumbUrl: "/img1.png",
  },
  {
    title: "HRM-Text: Efficient Pretraining Beyond Scaling",
    authors: "Guan Wang, Changling Liu, Chenyu Wang, +6 authors",
    date: "May 20, 2026",
    showAuthors: true,
    description: "The current pretraining paradigm relies on massive compute and internet-scale raw text, creating a barrier to foundational research. We propose HRM-Text, a biologically-inspired multi-timescale pretraining architecture modeled on the frontoparietal loop, enabling sample-efficient learning without raw scale.",
    upvotes: "3.2K",
    repos: "3.3K",
    citations: "10",
    tags: [
      { label: "Language Modeling", color: "green" },
      { label: "Pretraining", color: "gray" },
      { label: "Reasoning", color: "purple" },
    ],
    methods: ["Pre-training", "Reasoning model", "RoPE", "Transformer"],
    sotaBenchmarks: ["ARC-Challenge"],
    sotaRank: "3",
    sotaRankLabel: "BabyLM Benchmark",
    sotaExtra: "",
    thumbUrl: "/img2.png",
  },
  {
    title: "MolmoMotion: Forecasting Point Trajectories in 3D with Language Instruction",
    authors: "Jianing Zhang, Chenhao Zheng, Yajun Yang, +10 authors",
    date: "Jun 17, 2026",
    showAuthors: true,
    description: "Motion forecasting is central to visual intelligence: agents must anticipate how objects will move to plan actions and reason about physical interactions. We argue that 3D points in world coordinates provide a general class-agnostic, view-stable representation and introduce MolmoMotion to predict them from language instructions.",
    upvotes: "2.7K",
    repos: "2.8K",
    citations: "2",
    tags: [
      { label: "Image Understanding", color: "blue" },
      { label: "Robotics", color: "purple" },
      { label: "World Models", color: "green" },
    ],
    methods: ["Diffusion Transformer (DiT)", "Flow matching", "Transformer"],
    sotaBenchmarks: ["TAPVid-3D"],
    sotaRank: "2",
    sotaRankLabel: "DynPoint Benchmark",
    sotaExtra: "",
    thumbUrl: "/img3.png",
  },
  {
    title: "Rethinking Generalization in Reasoning SFT: A Conditional Analysis on Optimization, Data, and Model Capability",
    authors: "Qihan Ren, Peng Wang, Ruikun Cai, +8 authors",
    date: "Apr 8, 2026",
    showAuthors: true,
    description: "A prevailing narrative holds that SFT memorizes while RL generalizes. We revisit this claim for reasoning SFT with long chain-of-thought supervision and find that cross-domain generalization is conditional, jointly shaped by optimization dynamics, training data diversity, and base model capability.",
    upvotes: "4.5K",
    repos: "4.6K",
    citations: "30",
    tags: [
      { label: "Language Modeling", color: "green" },
      { label: "Reasoning", color: "purple" },
      { label: "Reinforcement Learning", color: "blue" },
    ],
    methods: ["Chain-of-Thought (CoT)", "Fine-tuning", "Post-training", "Qwen3"],
    sotaBenchmarks: ["MATH-500"],
    sotaRank: "3",
    sotaRankLabel: "GSM8K",
    sotaExtra: "",
    thumbUrl: "/img4.png",
  },
  {
    title: "Introducing Gemma 4 12B: a unified, encoder-free multimodal model",
    authors: "Google DeepMind",
    date: "Jun 3, 2026",
    showAuthors: true,
    description: "Gemma 4 12B is Google DeepMind's encoder-free multimodal model that projects raw image patches and audio directly into the LLM backbone, targeting laptop deployment with 16GB VRAM while delivering reasoning and agentic performance approaching the larger Gemma 4 26B MoE.",
    upvotes: "9.1K",
    repos: "9.2K",
    citations: "2",
    tags: [
      { label: "Agents", color: "blue" },
      { label: "Audio Understanding", color: "blue" },
      { label: "Coding Agents", color: "purple" },
      { label: "Image Understanding", color: "blue" },
      { label: "Language Modeling", color: "green" },
    ],
    methods: ["Long Context", "Omni Models", "Post-training", "RMSNorm", "Function calling"],
    sotaBenchmarks: ["MMMU", "MathVista"],
    sotaRank: "2",
    sotaRankLabel: "LiveCodeBench (v5)",
    sotaExtra: "",
    thumbUrl: "/img1.png",
  },
  {
    title: "Stable Audio 3",
    authors: "Zach Evans, Julian D. Parker, Matthew Rice, +4 authors",
    date: "May 18, 2026",
    showAuthors: true,
    description: "Stable Audio 3 is a family of fast latent diffusion models (small, medium, large) for variable-length audio generation and editing. We also support inpainting, enabling targeted audio editing while preserving surrounding context, making Stable Audio 3 a versatile tool for both creation and post-production.",
    upvotes: "5.8K",
    repos: "5.9K",
    citations: "1",
    tags: [
      { label: "Audio Generation", color: "blue" },
      { label: "Audio Editing", color: "green" },
      { label: "Multimodal", color: "orange" },
    ],
    methods: ["Autoencoder (AE)", "Diffusion", "Inpainting", "Post-training"],
    sotaBenchmarks: ["MusicCaps", "AudioCaps"],
    sotaRank: "2",
    sotaRankLabel: "FAD (AudioSet)",
    sotaExtra: "",
    thumbUrl: "/img2.png",
  },
  {
    title: "LocateAnything: Fast and High-Quality Vision-Language Grounding with Parallel Box Decoding",
    authors: "Shihao Wang, Shilong Liu, Yuanguo Kuang, +10 authors",
    date: "May 26, 2026",
    showAuthors: true,
    description: "Vision-language models commonly formulate visual grounding as a coordinate-token generation problem. This token-by-token decoding mismatches the coupled structure of box geometry and creates a practical inference bottleneck. We propose parallel box decoding to solve both issues simultaneously.",
    upvotes: "4.6K",
    repos: "4.7K",
    citations: "15",
    tags: [
      { label: "Image Understanding", color: "blue" },
      { label: "Language Modeling", color: "green" },
      { label: "Object Detection", color: "orange" },
    ],
    methods: ["ColPaLi", "Deformable Attention", "DETR", "Faster R-CNN"],
    sotaBenchmarks: ["RefCOCO", "RefCOCO+"],
    sotaRank: "2",
    sotaRankLabel: "Flickr30k Entities",
    sotaExtra: "",
    thumbUrl: "/img3.png",
  },
];